### ISSUE TITLE
Unit Testing Date Test Cases

### ISSUE THREAD

**Issue by airflow101** [Please-A-Plus/COMP3111-T24-deCOVID#13]
date checking for isBefore and isAfter needs further checking; noted for unit testing

_Originally posted by @airflow101 in https://github.com/Please-A-Plus/COMP3111-T24-deCOVID/issues/12#issuecomment-980648846_

**Comment by rstanuwijaya** [comment]
can you describe the bug?

**Comment by airflow101** [comment]
test cases for date checking has been made
